<?php

use Illuminate\Database\Seeder;

class MenuItemsTableCustomizationsSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('menu_items')->delete();
        
        \DB::table('menu_items')->insert(array (
            0 => 
            array (
                'id' => 1,
                'menu_id' => 1,
                'title' => 'Panel de Control',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-home',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 1,
                'created_at' => '2018-08-13 13:29:11',
                'updated_at' => '2018-08-21 20:58:01',
                'route' => 'voyager.dashboard',
                'parameters' => 'null',
            ),
            1 => 
            array (
                'id' => 2,
                'menu_id' => 1,
                'title' => 'Media',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-images',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 5,
                'created_at' => '2018-08-13 13:29:11',
                'updated_at' => '2018-08-21 20:57:28',
                'route' => 'voyager.media.index',
                'parameters' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'menu_id' => 1,
                'title' => 'Usuarios',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-person',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 3,
                'created_at' => '2018-08-13 13:29:11',
                'updated_at' => '2018-08-21 20:57:28',
                'route' => 'voyager.users.index',
                'parameters' => 'null',
            ),
            3 => 
            array (
                'id' => 4,
                'menu_id' => 1,
                'title' => 'Roles',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-lock',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 4,
                'created_at' => '2018-08-13 13:29:11',
                'updated_at' => '2018-08-21 20:57:28',
                'route' => 'voyager.roles.index',
                'parameters' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'menu_id' => 1,
                'title' => 'Herramientas',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-tools',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 6,
                'created_at' => '2018-08-13 13:29:11',
                'updated_at' => '2018-08-21 20:57:28',
                'route' => NULL,
                'parameters' => '',
            ),
            5 => 
            array (
                'id' => 6,
                'menu_id' => 1,
                'title' => 'Menu Builder',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-list',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 1,
                'created_at' => '2018-08-13 13:29:11',
                'updated_at' => '2018-08-13 21:41:54',
                'route' => 'voyager.menus.index',
                'parameters' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'menu_id' => 1,
                'title' => 'Base de Datos',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-data',
                'color' => '#000000',
                'parent_id' => 5,
                'order' => 2,
                'created_at' => '2018-08-13 13:29:11',
                'updated_at' => '2018-08-13 21:41:54',
                'route' => 'voyager.database.index',
                'parameters' => 'null',
            ),
            7 => 
            array (
                'id' => 8,
                'menu_id' => 1,
                'title' => 'Compass',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-compass',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 3,
                'created_at' => '2018-08-13 13:29:11',
                'updated_at' => '2018-08-13 21:41:54',
                'route' => 'voyager.compass.index',
                'parameters' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'menu_id' => 1,
                'title' => 'BREAD',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-bread',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 4,
                'created_at' => '2018-08-13 13:29:11',
                'updated_at' => '2018-08-13 21:41:54',
                'route' => 'voyager.bread.index',
                'parameters' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'menu_id' => 1,
                'title' => 'Configuración del Sitio',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-settings',
                'color' => '#000000',
                'parent_id' => 22,
                'order' => 1,
                'created_at' => '2018-08-13 13:29:11',
                'updated_at' => '2018-08-21 12:58:36',
                'route' => 'voyager.settings.index',
                'parameters' => 'null',
            ),
            10 => 
            array (
                'id' => 14,
                'menu_id' => 1,
                'title' => 'Hooks',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-hook',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 5,
                'created_at' => '2018-08-13 13:29:14',
                'updated_at' => '2018-08-13 21:41:54',
                'route' => 'voyager.hooks',
                'parameters' => NULL,
            ),
            11 => 
            array (
                'id' => 22,
                'menu_id' => 1,
                'title' => 'Configuración',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-settings',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 7,
                'created_at' => '2018-08-13 21:41:36',
                'updated_at' => '2018-08-21 20:57:28',
                'route' => NULL,
                'parameters' => '',
            ),
            12 => 
            array (
                'id' => 23,
                'menu_id' => 1,
                'title' => 'Estados',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 26,
                'order' => 1,
                'created_at' => '2018-08-13 23:18:04',
                'updated_at' => '2018-08-21 12:34:45',
                'route' => 'voyager.states.index',
                'parameters' => 'null',
            ),
            13 => 
            array (
                'id' => 24,
                'menu_id' => 1,
                'title' => 'Municipios',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => NULL,
                'parent_id' => 26,
                'order' => 2,
                'created_at' => '2018-08-14 00:33:28',
                'updated_at' => '2018-08-21 12:34:46',
                'route' => 'voyager.municipios.index',
                'parameters' => NULL,
            ),
            14 => 
            array (
                'id' => 25,
                'menu_id' => 1,
                'title' => 'Parroquias',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => NULL,
                'parent_id' => 26,
                'order' => 3,
                'created_at' => '2018-08-14 01:04:41',
                'updated_at' => '2018-08-21 12:34:47',
                'route' => 'voyager.parroquias.index',
                'parameters' => NULL,
            ),
            15 => 
            array (
                'id' => 27,
                'menu_id' => 1,
                'title' => 'Estados',
                'url' => '/admin/states',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 22,
                'order' => 2,
                'created_at' => '2018-08-21 12:42:19',
                'updated_at' => '2018-08-21 12:48:46',
                'route' => NULL,
                'parameters' => '',
            ),
            16 => 
            array (
                'id' => 28,
                'menu_id' => 1,
                'title' => 'Municipios',
                'url' => '/admin/municipios',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 22,
                'order' => 3,
                'created_at' => '2018-08-21 12:43:33',
                'updated_at' => '2018-08-21 12:48:46',
                'route' => NULL,
                'parameters' => '',
            ),
            17 => 
            array (
                'id' => 29,
                'menu_id' => 1,
                'title' => 'Parroquias',
                'url' => '/admin/parroquias',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => 22,
                'order' => 4,
                'created_at' => '2018-08-21 12:43:48',
                'updated_at' => '2018-08-21 12:48:46',
                'route' => NULL,
                'parameters' => '',
            ),
        ));
        
        
    }
}