-- MySQL Script generated by MySQL Workbench
-- Sun Oct 14 20:07:42 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sisgecundb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sisgecundb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sisgecundb` DEFAULT CHARACTER SET utf8 ;
USE `sisgecundb` ;

-- -----------------------------------------------------
-- Table `sisgecundb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisgecundb`.`Usuario` (
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sisgecundb`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisgecundb`.`usuarios` (
  `id` INT NOT NULL,
  `cedula` VARCHAR(191) NOT NULL,
  `primer nombre` VARCHAR(191) NOT NULL,
  `segundo nombre` VARCHAR(191) NULL,
  `primer apellido` VARCHAR(191) NOT NULL,
  `segundo apellido` VARCHAR(191) NULL,
  `password` VARCHAR(191) NOT NULL,
  `telefono_celular` VARCHAR(191) NOT NULL,
  `sexo` VARCHAR(191) NOT NULL,
  `login` VARCHAR(191) NOT NULL,
  `telefono1` VARCHAR(191) NULL,
  `telefono2` VARCHAR(191) NULL,
  `rif` VARCHAR(191) NULL,
  `email` VARCHAR(191) NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sisgecundb`.`instituciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisgecundb`.`instituciones` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(191) NOT NULL,
  `siglas` VARCHAR(191) NOT NULL,
  `direccion` VARCHAR(191) NULL,
  `rif` VARCHAR(191) NULL,
  `matricula_estudiantil` INT NOT NULL,
  `cantidad_matricula_femeninca` INT NOT NULL,
  `cantidad_matricula_masculino` INT NOT NULL,
  `fax` VARCHAR(191) NULL,
  `correo_electronico` VARCHAR(191) NOT NULL,
  `codigo_postal` VARCHAR(191) NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sisgecundb`.`descripciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisgecundb`.`descripciones` (
  `id` INT NOT NULL,
  `tiene_cuarto_frio` TINYINT(1) NULL,
  `cuarto_frio_operativo` TINYINT(1) NULL,
  `capacidad_cuartofrio` INT NULL,
  `tiene_cuarto_congelacion` TINYINT(1) NULL,
  `capacidad_cuarto_congelacion` VARCHAR(191) NULL,
  `cuarto_congelacion_operativo` TINYINT(1) NULL,
  `tiene_utensilios` TINYINT(1) NULL,
  `cantidad_platos` INT NULL,
  `cantidad_cubiertos` INT NULL,
  `cantidad_vasos` INT NULL,
  `tienen_extintores` TINYINT(1) NULL,
  `cantidad_extintores` INT NULL,
  `extintores_operativo` TINYINT(1) NULL,
  `tanquilla_agualluvia` TINYINT(1) NOT NULL,
  `tanquilla_aguapotable` TINYINT(1) NOT NULL,
  `tanquilla_aguaresidual` TINYINT(1) NOT NULL,
  `tanquilla_electricidad` TINYINT(1) NOT NULL,
  `medidor_electricidad` TINYINT(1) NULL,
  `sum_aguapotable` TINYINT(1) NULL,
  `iluminacion_natural` TINYINT(1) NOT NULL,
  `iluminacion_artificial` TINYINT(1) NOT NULL,
  `electricidad_110` TINYINT(1) NOT NULL,
  `electricidad_220` TINYINT(1) NOT NULL,
  `internet` TINYINT(1) NOT NULL,
  `extension` TINYINT(1) NOT NULL,
  `linea_directa` TINYINT(1) NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sisgecundb`.`comedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisgecundb`.`comedores` (
  `id` INT NOT NULL,
  `codigosica` VARCHAR(191) NOT NULL,
  `estatus` VARCHAR(191) NOT NULL,
  `observacion` VARCHAR(191) NOT NULL,
  `descripcion` VARCHAR(191) NOT NULL,
  `capacidad_atencion` INT NOT NULL,
  `cantidad_estudiantes_desayuno` INT NOT NULL,
  `cantidad_Estudiantes_almuerzo` INT NOT NULL,
  `cantidad_Estudiantes_cena` INT NOT NULL,
  `menu_establecido` TINYINT(1) NULL,
  `cant_Estudiantes_femenino_discap` INT NULL,
  `cant_estudiantes_masculino_discap` INT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `instituciones_id` INT NOT NULL,
  `descripciones_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_comedores_instituciones1`
    FOREIGN KEY (`instituciones_id`)
    REFERENCES `sisgecundb`.`instituciones` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comedores_descripciones1`
    FOREIGN KEY (`descripciones_id`)
    REFERENCES `sisgecundb`.`descripciones` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sisgecundb`.`comedor_responsable`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisgecundb`.`comedor_responsable` (
  `id` INT NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `usuarios_id` INT NOT NULL,
  `comedores_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_comedor_responsable_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `sisgecundb`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comedor_responsable_comedores1`
    FOREIGN KEY (`comedores_id`)
    REFERENCES `sisgecundb`.`comedores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sisgecundb`.`administradores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisgecundb`.`administradores` (
  `id` INT NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `usuarios_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_administradores_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `sisgecundb`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sisgecundb`.`estados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisgecundb`.`estados` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(191) NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sisgecundb`.`ciudades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisgecundb`.`ciudades` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(191) NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sisgecundb`.`municipios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisgecundb`.`municipios` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(191) NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `ciudades_id` INT NOT NULL,
  `estados_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_municipios_ciudades1`
    FOREIGN KEY (`ciudades_id`)
    REFERENCES `sisgecundb`.`ciudades` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_municipios_estados1`
    FOREIGN KEY (`estados_id`)
    REFERENCES `sisgecundb`.`estados` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sisgecundb`.`institucion_estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisgecundb`.`institucion_estado` (
  `id` INT NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `instituciones_id` INT NOT NULL,
  `estados_id` INT NOT NULL,
  `estados_Region_idRegion` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_institucion_estado_instituciones1`
    FOREIGN KEY (`instituciones_id`)
    REFERENCES `sisgecundb`.`instituciones` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_institucion_estado_estados1`
    FOREIGN KEY (`estados_id`)
    REFERENCES `sisgecundb`.`estados` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sisgecundb`.`bandejas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisgecundb`.`bandejas` (
  `id` INT NOT NULL,
  `fecha` DATE NULL,
  `observacion` VARCHAR(191) NULL,
  `cantidad_bandejas_servidas` INT(11) NULL,
  `cantidad_gramaje_total` VARCHAR(191) NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `comedores_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_bandejas_comedores1`
    FOREIGN KEY (`comedores_id`)
    REFERENCES `sisgecundb`.`comedores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sisgecundb`.`regiones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisgecundb`.`regiones` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(191) NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `estados_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_regiones_estados1`
    FOREIGN KEY (`estados_id`)
    REFERENCES `sisgecundb`.`estados` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sisgecundb`.`MPPEUCT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisgecundb`.`MPPEUCT` (
  `id` INT NOT NULL,
  `cargo` VARCHAR(191) NOT NULL,
  `dependencia` VARCHAR(191) NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `usuarios_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_MPPEUCT_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `sisgecundb`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sisgecundb`.`porciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisgecundb`.`porciones` (
  `id` INT NOT NULL,
  `gramaje` VARCHAR(191) NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sisgecundb`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisgecundb`.`productos` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(191) NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `porciones_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_productos_porciones1`
    FOREIGN KEY (`porciones_id`)
    REFERENCES `sisgecundb`.`porciones` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sisgecundb`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisgecundb`.`categorias` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(191) NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `productos_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_categorias_productos1`
    FOREIGN KEY (`productos_id`)
    REFERENCES `sisgecundb`.`productos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sisgecundb`.`productos_recibidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisgecundb`.`productos_recibidos` (
  `id` INT NOT NULL,
  `fecha_recibido` VARCHAR(191) NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sisgecundb`.`productos_enviados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisgecundb`.`productos_enviados` (
  `id` INT NOT NULL,
  `fecha_envio` VARCHAR(191) NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sisgecundb`.`envios_productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisgecundb`.`envios_productos` (
  `id` INT NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `MPPEUCT_id` INT NOT NULL,
  `productos_recibidos_id` INT NOT NULL,
  `productos_enviados_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_envios_productos_MPPEUCT1`
    FOREIGN KEY (`MPPEUCT_id`)
    REFERENCES `sisgecundb`.`MPPEUCT` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_envios_productos_productos_recibidos1`
    FOREIGN KEY (`productos_recibidos_id`)
    REFERENCES `sisgecundb`.`productos_recibidos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_envios_productos_productos_enviados1`
    FOREIGN KEY (`productos_enviados_id`)
    REFERENCES `sisgecundb`.`productos_enviados` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sisgecundb`.`comedor_envio_producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisgecundb`.`comedor_envio_producto` (
  `id` INT NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `envios_productos_id` INT NOT NULL,
  `comedores_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_comedor_envio_producto_envios_productos1`
    FOREIGN KEY (`envios_productos_id`)
    REFERENCES `sisgecundb`.`envios_productos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comedor_envio_producto_comedores1`
    FOREIGN KEY (`comedores_id`)
    REFERENCES `sisgecundb`.`comedores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sisgecundb`.`solicitudes_productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisgecundb`.`solicitudes_productos` (
  `id` INT NOT NULL,
  `fecha` DATE NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `envios_productos_id` INT NOT NULL,
  `comedores_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_solicitudes_productos_envios_productos1`
    FOREIGN KEY (`envios_productos_id`)
    REFERENCES `sisgecundb`.`envios_productos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_solicitudes_productos_comedores1`
    FOREIGN KEY (`comedores_id`)
    REFERENCES `sisgecundb`.`comedores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sisgecundb`.`parroquias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisgecundb`.`parroquias` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(191) NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `municipios_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_parroquias_municipios1`
    FOREIGN KEY (`municipios_id`)
    REFERENCES `sisgecundb`.`municipios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sisgecundb`.`comedor_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisgecundb`.`comedor_usuario` (
  `id` INT NOT NULL,
  `cargo` VARCHAR(191) NOT NULL,
  `tipo_responsable` VARCHAR(191) NULL,
  `unidad_institucion` VARCHAR(191) NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `usuarios_id` INT NOT NULL,
  `comedores_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_comedor_usuario_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `sisgecundb`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comedor_usuario_comedores1`
    FOREIGN KEY (`comedores_id`)
    REFERENCES `sisgecundb`.`comedores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sisgecundb`.`Tipo_Bandeja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisgecundb`.`Tipo_Bandeja` (
  `id` INT NOT NULL,
  `tipo_bandeja` VARCHAR(191) NOT NULL COMMENT 'desayuno, almuerzo, merienda, cena',
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `bandejas_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Tipo_Bandeja_bandejas1`
    FOREIGN KEY (`bandejas_id`)
    REFERENCES `sisgecundb`.`bandejas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'desayuno, almuerzo, merienda, cena';


-- -----------------------------------------------------
-- Table `sisgecundb`.`bandeja_productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisgecundb`.`bandeja_productos` (
  `id` INT NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `bandejas_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_bandeja_productos_bandejas1`
    FOREIGN KEY (`bandejas_id`)
    REFERENCES `sisgecundb`.`bandejas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sisgecundb`.`comedor_producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisgecundb`.`comedor_producto` (
  `id` INT NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `envios_productos_id` INT NOT NULL,
  `productos_id` INT NOT NULL,
  `productos_Categoria_idCategoria` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_comedor_producto_envios_productos1`
    FOREIGN KEY (`envios_productos_id`)
    REFERENCES `sisgecundb`.`envios_productos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comedor_producto_productos1`
    FOREIGN KEY (`productos_id`)
    REFERENCES `sisgecundb`.`productos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sisgecundb`.`despachar_responsables`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisgecundb`.`despachar_responsables` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(191) NULL,
  `apellido` VARCHAR(191) NULL,
  `telefono_celular` VARCHAR(191) NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sisgecundb`.`productos_despachados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisgecundb`.`productos_despachados` (
  `id` INT NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `despachar_responsables_id` INT NOT NULL,
  `productos_enviados_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_producto_enviado_despachar_responsable_despachar_responsab1`
    FOREIGN KEY (`despachar_responsables_id`)
    REFERENCES `sisgecundb`.`despachar_responsables` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_producto_enviado_despachar_responsable_productos_enviados1`
    FOREIGN KEY (`productos_enviados_id`)
    REFERENCES `sisgecundb`.`productos_enviados` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sisgecundb`.`almacenes_productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisgecundb`.`almacenes_productos` (
  `id` INT NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `comedores_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_almacenes_productos_comedores1`
    FOREIGN KEY (`comedores_id`)
    REFERENCES `sisgecundb`.`comedores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sisgecundb`.`configuraciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisgecundb`.`configuraciones` (
  `id` INT NOT NULL,
  `configuracion` VARCHAR(191) NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `administradores_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_configuraciones_administradores1`
    FOREIGN KEY (`administradores_id`)
    REFERENCES `sisgecundb`.`administradores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sisgecundb`.`nutricionistas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisgecundb`.`nutricionistas` (
  `id` INT NOT NULL,
  `estatus` VARCHAR(191) NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `usuarios_id` INT NOT NULL,
  `comedores_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_nutricionistas_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `sisgecundb`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_nutricionistas_comedores1`
    FOREIGN KEY (`comedores_id`)
    REFERENCES `sisgecundb`.`comedores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sisgecundb`.`aireacondicionados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisgecundb`.`aireacondicionados` (
  `id` INT NOT NULL,
  `estatus` VARCHAR(191) NULL,
  `capacidad_enfiramiento` VARCHAR(191) NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `comedores_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_aireacondicionados_comedores1`
    FOREIGN KEY (`comedores_id`)
    REFERENCES `sisgecundb`.`comedores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
